### ISSUE TITLE
ensure AA, WCAG 2.1 compliant accessibility ( color schemes, keyboard navigation)

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#11]
I just installed this to test. I am **only** commenting on the accessibility requirement - nothing else.

Every page has basic accessibility errors

For example the 
**new article page**
- button-name: Buttons must have discernible text (x1) WCAG 4.1.2
- color-contrast: Elements must have sufficient color contrast (x7) WCAG 1.4.3
- duplicate-id-aria: IDs used in ARIA and labels must be unique (x1) WCAG 4.1.1
- duplicate-id: id attribute value must be unique (x1) WCAG 4.1.1
- label: Form elements must have labels (x1) WCAG 1.3.1, WCAG 3.3.2
- link-name: Links must have discernible text (x10) WCAG 2.4.4, WCAG 4.1.2

**admin template styles page**

- color-contrast: Elements must have sufficient color contrast (x4) WCAG 1.4.3
- label: Form elements must have labels (x1) WCAG 1.3.1, WCAG 3.3.2
- link-name: Links must have discernible text (x4) WCAG 2.4.4, WCAG 4.1.2

As for the menu - that has too many accessibility errors to even begin to list. Just switch on a screen reader 

Keyboard navigation looks like it has been completely forgotten as well. 
- There are onhover information (tooltips/popovers??) that can not be accessed from the keyboard eg the template styles information
- There is no way using the keyboard when creating content to navigate to any collapsed item in the accordian

**Comment by kawshar** [comment]
Thank you very much. All points have been noted. I will forward it to our accessibility expert. I hope we can fix all the issues as soon as possible.
