### ISSUE TITLE
Available updates percentage

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#115]
### Steps to reproduce the issue
Install something that has available updates eg an older german language file from http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6418

### Actual result
![image](https://user-images.githubusercontent.com/1296369/69916038-c4804780-144d-11ea-992a-083056cd097a.png)

### Additional comments
It's pretty but if it is going to just remove 1% for each extension then it is very misleading

**Comment by ahamed** [comment]
It's actually something `99.99%` but we take the `floor` of the fraction.
The total calculation is- If `Joomla!` is outdated then the `50%` of the system is outdated and the other `50%` is all of the extensions.

**Comment by brianteeman** [comment]
so with 10 outdated extensions it produces a value of ?

**Comment by ahamed** [comment]
The condition is Joomla! alone = `50%` + All extensions = `50%`. So if 10 extensions are outdated and say there are 120 installed extensions. Then the calculation would be- 

`total_updated = (120 - 10) = 110`
`update_percent = (110 * 100) / 120 = 91.67%`

50% of `update_percent` is `91.67 * (50 / 100)  = 45.83%`
`// As all extensions = 50% and Joomla! = 50%`

IF Joomla! updated then `total_percent = 45.83 + 50 = 95.83%`, Otherwise it is `45.83%` 

The floor result is `95%` or `45%`

**Comment by brianteeman** [comment]
So the problem is that you are not calculating the number of extensions correctly.

What you are doing is a count of everything in the extensions table

https://github.com/joomla-projects/j4adminui/blob/caa81fca76b54b2a7561f6c69862c56dc8c6e8bd/administrator/modules/mod_extension_updates/Helper/ExtensionUpdatesHelper.php#L153-L163

But that is not correct. You should only be counting the number of non-core extensions not all the extensions. To do this you should be the functions in the ExtensionHelper

**Comment by ahamed** [comment]
Okay, this is a very much valid issue. We should count the core-extensions with Joomla! (The 50% valuation). Thank you so much @brianteeman. You can raise a separate issue for that so that I can solve this ASAP.

**Comment by brianteeman** [comment]
No need for a new issue

**Comment by ahamed** [comment]
@brianteeman,
I cannot understand the problem of language packages. At the table `#__updates` there are several elements with type `package` which has an `extension_id = 0` and they are obviously not at `#__extensions` table. Then what are these?

**Comment by brianteeman** [comment]
if an extension is listed in the array I referred to above then it should not be counted as an extension in your calculations. On a clean install the count of extensions for the purposes of this module should be 0

**Comment by ahamed** [comment]
When I installed an outdated version of `German DE` language then it is not on the `#__extensions` table but the system says one extension is outdated.

<img width="1168" alt="Screenshot 2019-12-05 at 4 10 55 PM" src="https://user-images.githubusercontent.com/5783354/70225776-dfb6c400-1779-11ea-956f-0427bbd11a93.png">

As it is not on the `#__extensions` table so I cannot catch it as an installed extension.

**Comment by ahamed** [comment]
@brianteeman,
It was my bad. After installing I get it on the `#__extensions` table.

**Comment by thaoredweb** [comment]
I think we can close this one. It is fine now
![a4](https://user-images.githubusercontent.com/30283123/70789605-e8d11200-1dc5-11ea-90e1-bf7fbb012b39.png)
