### ISSUE TITLE
user list - user notes

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#125]
### Steps to reproduce the issue
create a usernote for a user

### Expected result
nice display of the links in the users list

### Actual result
![image](https://user-images.githubusercontent.com/1296369/69917780-b89e8080-1461-11ea-9f1c-f1030a99dd7f.png)

**Comment by VanTrieuThanh** [comment]
I has fine but when I it on class="btn btn-secondary btn-sm dropdown-toggle dropdown-toggle-split" 
![345](https://user-images.githubusercontent.com/44457418/70319790-ba978380-1855-11ea-8950-f53694a4931a.PNG)
 it has show drop-layout 
![346](https://user-images.githubusercontent.com/44457418/70319810-c84d0900-1855-11ea-83fb-0b9081f5898b.PNG)
