### ISSUE TITLE
Time select

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#127]
### Steps to reproduce the issue
Use any field using the calendar 

### Expected result
Time is displayed correctly
![image](https://user-images.githubusercontent.com/1296369/69917909-3a42de00-1463-11ea-861d-c5139cd524e4.png)

### Actual result

![image](https://user-images.githubusercontent.com/1296369/69917914-44fd7300-1463-11ea-899a-48a38730f026.png)

**Comment by delowardev** [comment]
![j4calendar](https://user-images.githubusercontent.com/17360543/70026176-552f6280-15c9-11ea-95c2-f5636c5bbcfc.png)


I don't get the issue, this is the current calendar. Can you please explain what exactly the problem  is?

**Comment by brianteeman** [comment]
It works on firefox but on chrome for windows I still have the reported problem

**Comment by joomlacorner** [comment]
Confirm issue. I'm tested on Firefox. 

**Contents->Articles->Add New Article** 
  and then click on Publishing block.

Start Publishing
![Screen Shot 2562-12-03 at 23 58 31](https://user-images.githubusercontent.com/144291/70072237-2c3eba00-1629-11ea-8388-00611d56a009.png)

Finish Publishing
![Screen Shot 2562-12-03 at 23 58 41](https://user-images.githubusercontent.com/144291/70072254-33fe5e80-1629-11ea-8a80-f9a58fc229b6.png)

Created Date
![Screen Shot 2562-12-03 at 23 58 54](https://user-images.githubusercontent.com/144291/70072291-45e00180-1629-11ea-8dd4-0e058001acd0.png)
