### ISSUE TITLE
Image copyright??

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#130]
These images are all copyright https://icons8.com/ and https://www.instagram.com/bogdanmagenta/  and can not be used unless OSM arranges for a licence to use them.

![image](https://user-images.githubusercontent.com/1296369/69919161-01f6cc00-1472-11ea-908c-0ab7a31c95c1.png)

**Comment by marcodings** [comment]
@kawshar please address

**Comment by kawshar** [comment]
Checking with the team. Might be a placeholder and reserved to change later. I will talk to the team tomorrow as they already left the office.

Thank you

**Comment by brianteeman** [comment]
You really need to be very careful with copyright. These images are being served from a joomla property which makes joomla liable for any copyright infringement

**Comment by kawshar** [comment]
Yes, definitely. Already talked to the team and they said that they put it as a placeholder. However, they are on it now and designing something on their own.

Thanks

**Comment by brianteeman** [comment]
Please make this an absolute priority as we should not infringe anyone's copyright. If it was someone infringing our copyright we would be rightfully angry.

**Comment by kawshar** [comment]
I will make sure about that.

**Comment by brianteeman** [comment]
As previously requested please make this a priority.

**Comment by kawshar** [comment]
It will be delivered in the next 2-3 days. The designer took an entire week's leave due to health concerns.

Thanks

**Comment by kawshar** [comment]
Hi @brianteeman, what do you think of this? This one is for global check-in.
![01](https://user-images.githubusercontent.com/26220745/70601983-8e954d00-1c1d-11ea-9710-f85a0f200f4b.jpg)

Proof of the original design :)
![IMG_6348](https://user-images.githubusercontent.com/26220745/70602118-d9af6000-1c1d-11ea-854b-06566fb05461.jpg)

**Comment by brianteeman** [comment]
Not for me to comment as I have no design skills. I just want to not abuse someone else copyright

**Comment by kawshar** [comment]
I have an idea. Let me know what do you think about that. We can use the following designs, for now, I mean for the next few days. In the meantime, we can design a character that will be more meaningful for Joomla which can be used as a final character.

But, in order to design a meaningful Joomla character, it will take 3-5 days.

Thanks

**Comment by brianteeman** [comment]
I only care that we get rid of the copyright images from joomla property asap.

**Comment by kawshar** [comment]
We will submit a PR today.

**Comment by brianteeman** [comment]
Fixed in #157
