### ISSUE TITLE
Template style filters

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#131]
### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/1296369/69919489-27d1a000-1475-11ea-8a53-3894de08d6ff.png)

### Expected result
The "select a menu" dropdown should be only for Site template styles
Or if you intended it to be a new feature and it should be available for Admin template styles then it is showing the wrong menus in the dropdown

**Comment by ahamed** [comment]
I think there is no need for filtering here. What's your opinion @brianteeman?
