### ISSUE TITLE
Collapsed module icon

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#137]
### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1296369/69956396-c7377700-14f7-11ea-86cc-e68e7643379c.png)

### Expected result
The icon will change (just as it does in the menu) to indicate expand or collapse

### Actual result
The icon is always the same

**Comment by ahamed** [comment]
Toggle button functionality fixed on another PR #90 . But this has a dependency on PR #87. The #90 has already been merged. When the #87 will be merged then you can find the solution to this issue.

The #87 has one positive review and as Joomla's rule,  there needs another positive review to merge the PR. Could you please help? @brianteeman
