### ISSUE TITLE
create an article module

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#138]
![image](https://user-images.githubusercontent.com/1296369/69957199-0f579900-14fa-11ea-82fe-482dbcce449c.png)

I am not sure if this is a bug or the intended behaviour but I expected to press save and the article would be created. I did not expect to press save and then the article edit would open etc

**Comment by ahamed** [comment]
It's intentional. Do you have any suggestion that how could we improve it?

**Comment by brianteeman** [comment]
I would have expected it to be saved as it is in the module. Otherwise its not a "quick" article at all.

**Comment by kawshar** [comment]
> I would have expected it to be saved as it is in the module. Otherwise its not a "quick" article at all.

Stay on the same page? Then what? Will you please share more details?

**Comment by marcodings** [comment]
Stay on page with "Article created message" and a link to edit the article

**Comment by brianteeman** [comment]
@kawshar sorry for the delay in responding i missed the notification.

Yes exactly what @marcodings said - otherwise there really is no point in having the module

**Comment by kawshar** [comment]
Got it. Will be fixed. @ahamed07sajeeb please have a look.
