### ISSUE TITLE
Drag-n-Drop block issue at Dashboard page

### ISSUE THREAD

**Issue by davidnguyen-joomlashine** [joomla-projects/j4adminui#165]
### Steps to reproduce the issue
Go head over to the "Dashboard" page. Mouse over the "handle" icon of one of the blocks, your cursor will turn into "Grabbing" type, but the drag-n-drop does not work.

### Expected result
* To be able to arrange the block position by drag-n-drop function

### Actual result
* The drag-n-drop does not work
![Screenshot (2)](https://user-images.githubusercontent.com/58210348/70899164-a8bd9980-2028-11ea-9bdc-813f3105f4ae.png)

**Comment by ahamed** [comment]
At my end, it's working as it is. I think you need to run `npm run build:js && npm run build:css` command on your terminal and hard reload your browser.

**Comment by davidnguyen-joomlashine** [comment]
@ahamed07sajeeb you are right. Thank you
