### ISSUE TITLE
Easier testing ( nightly builds & launch.joomla.org)

### ISSUE THREAD

**Issue by marcodings** [joomla-projects/j4adminui#190]
Nightly builds
---------------------
Nightly builds are now availabe from https://developer.joomla.org/backend-template/

Launch.joomla.org
---------------------
Nightly builds will be made available from https://launch.joomla.org/ by choosing the "khonsu" option to install through the advanced settings when launching a site

**Comment by kawshar** [comment]
Khonsu option is not available.

**Comment by kawshar** [comment]
[Joomla_4.0.0-beta1-dev-Development-Full_Package.zip](https://github.com/joomla-projects/j4adminui/files/4157845/Joomla_4.0.0-beta1-dev-Development-Full_Package.zip)

Here is the build version btw.

Thanks

**Comment by kawshar** [comment]
[Joomla_4.0.0-unofficial-khonsu-dev-Development-Full_Package.zip](https://github.com/joomla-projects/j4adminui/files/4157858/Joomla_4.0.0-unofficial-khonsu-dev-Development-Full_Package.zip)

Here is the build version btw.

Thanks

**Comment by marcodings** [comment]
> Khonsu option is not available.

Not yet, this is being worked on by cloud-access, thats why i wrote "will be"

I removed you post with i download link as that will cause confusion. The nightly build
https://developer.joomla.org/backend-template/ holds a download link to an installable version that is updated every day automagically to reflect the status of the repository

**Comment by brianteeman** [comment]
@marcodings Thanks for creating that but could it please have a different filename as the current one clashes with the real one

**Comment by brianteeman** [comment]
and there is something wrong with the build script as the font used for the icons is not present

**Comment by exmmth** [comment]
> and there is something wrong with the build script as the font used for the icons is not present

@marcodings please fix file in path:
`administrator\templates\khonsu\scss\fonts\_joomla-fonts.scss`

lines 14-15
`  src: url("../../../../build/media_source/system/fonts/joomla-fonts.woff2") format("woff2"),
  url("../../../../build/media_source/system/fonts/joomla-fonts.woff") format("woff");`
to 
`  src: url("../../../../media/system/fonts/joomla-fonts.woff2") format("woff2"),
  url("../../../../media/system/fonts/joomla-fonts.woff") format("woff");`

@kawshar in github you have same problem in file, but in arhive #186 you have second variant.

**Comment by exmmth** [comment]
@marcodings  when we can launch Khonsu on https://launch.joomla.org/  ?
and fix lines #194 may be need to be replaced or rebuild files in folder administrator\templates\khonsu\css\

**Comment by exmmth** [comment]
> ## Nightly builds
> Nightly builds are now availabe from https://developer.joomla.org/backend-template/
> 
> ## Launch.joomla.org
> Nightly builds will be made available from https://launch.joomla.org/ by choosing the "khonsu" option to install through the advanced settings when launching a site

@marcodings @brianteeman there is a chance that you will fix it or you buried it?

**Comment by brianteeman** [comment]
It is not something I have access to fix - sorry

**Comment by exmmth** [comment]
> It is not something I have access to fix - sorry

Thank you for the answer! I understand, Marco Dings is silent, so I called you. 

In order for more people to be able to test the template and see successful solutions, we need to fix this problem as the first.

**Comment by brianteeman** [comment]
no comment

**Comment by exmmth** [comment]
> no comment

I thought you were in charge of management. If it is not, I apologize for disturbing.

English is not my native language.

**Comment by marcodings** [comment]
The project status changed : 
https://github.com/joomla-projects/j4adminui/issues/186#issuecomment-583064115
For that reason the project has been pulled from integration on launch.joomla.org

Problems with the nightly build are to be addressed through regular issues. The font's issue was reported by brian https://github.com/joomla-projects/j4adminui/issues/194.

**Comment by brianteeman** [comment]
Could you update the readme or the repo description so that the status is made clear and people dont waste their time, please
