### ISSUE TITLE
All icon fonts missing

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#194]
![image](https://user-images.githubusercontent.com/1296369/73848144-7574db00-481f-11ea-93db-46ffd8a3dc5c.png)

### Steps to reproduce the issue
Install the package from developer.joomla.org
![image](https://user-images.githubusercontent.com/1296369/73848219-9d643e80-481f-11ea-95c0-b59a80b6b1aa.png)

All the icon fonts are missing due to this error

https://github.com/joomla-projects/j4adminui/blob/b3c7be543754a5d111c7fa2c25e668b771f74c1f/administrator/templates/khonsu/scss/fonts/_joomla-fonts.scss#L14-L15

**Comment by kawshar** [comment]
Did you run npm ci?

**Comment by brianteeman** [comment]
i am referring to the prebuilt zip

**Comment by kawshar** [comment]
I just installed and could not find any issue 
![image](https://user-images.githubusercontent.com/26220745/73856089-25b60400-485f-11ea-9086-ed13389b458d.png)

Can someone please cross-check?

**Comment by kawshar** [comment]
@brianteeman you downloaded from this link, right? https://github.com/joomla-projects/j4adminui/files/4158949/Joomla_4.0.0-unofficial-khonsu-dev-Development-Full_Package.zip

**Comment by brianteeman** [comment]
This is the link that @marcodings gave and that I used
https://developer.joomla.org/backend-template/

The same can be seen using this
https://github.com/joomla/joomla-cms/issues/27758#issuecomment-582394630

You will almost certainly see on your local install that you have a build/media-source folder and thats why you have the font.

**Comment by kawshar** [comment]
I think the build was not correct.

**Comment by brianteeman** [comment]
That is why I wrote https://github.com/joomla-projects/j4adminui/issues/190#issuecomment-582416117

**Comment by wilsonge** [comment]
The build on jenkins uses the standard build script https://github.com/joomla-projects/j4adminui/blob/master/build/build.php should be reproducible - there's really nothing special happening in jenkins

It runs the command `php build/build.php --remote=origin/master --exclude-gzip --exclude-bzip2` to generate the zips

**Comment by exmmth** [comment]
> The build on jenkins uses the standard build script https://github.com/joomla-projects/j4adminui/blob/master/build/build.php should be reproducible - there's really nothing special happening in jenkins

Glad to see you! Thank you for you answer. We need do PR fix some files as I saw -  #190  

@kawshar I can try to do this PR I need you help to don't brake you "team build way".

@wilsonge in README different way to use this repo, this is promblem to need fix?

**Comment by wilsonge** [comment]
No - how we build the stable packages removes the developer dependencies required for local development. I can't see anything wrong with the readme.

How the files get fixed is one for the team here to work on :)
