### ISSUE TITLE
Size of module in dashboard

### ISSUE THREAD

**Issue by micker** [joomla-projects/j4adminui#26]
### Steps to reproduce the issue
edit last article module in dasboard
set 12 in bootstrap size

### Expected result
module take full width

### Actual result
no change

**Comment by ahamed** [comment]
The dashboard is designed with two columns grid system. So every module on the dashboard fits on 6 column width. This has been done for the drag & drop feature of the dashboard modules. Otherwise, it's not so easy for the users to arrange the dashboard.

**Comment by micker** [comment]
ok i understand
