### ISSUE TITLE
Joomla SVG logo not loading in installation page

### ISSUE THREAD

**Issue by arunsasi** [joomla-projects/j4adminui#3]
Image not loading from _../installation/template/images/logo-joomla.svg_

> installation/template/images/logo-joomla.svg was not found on this server.
<img width="522" alt="Screenshot 2019-10-18 at 11 04 40 PM" src="https://user-images.githubusercontent.com/270789/67115506-03d73980-f1fc-11e9-899c-8f78a6c197b6.png">

**Comment by kawshar** [comment]
Will be fixed.
