### ISSUE TITLE
Error in Help Menu

### ISSUE THREAD

**Issue by astridx** [joomla-projects/j4adminui#30]
### Steps to reproduce the issue

1. Click on `Help` and then on on `edit` near `Meet Joomlers`
![Help   Testui   Administration](https://user-images.githubusercontent.com/9974686/68163002-b37d0d00-ff59-11e9-944a-137d27e07d4d.png)

2. Then click on `Close` and you see the following `Error`.
![Error  0](https://user-images.githubusercontent.com/9974686/68163106-0bb40f00-ff5a-11e9-8fed-4b3c6304a117.png)

The same happens with all five items in the help board.

![Help   Testui   Administration(2)](https://user-images.githubusercontent.com/9974686/68163389-b3314180-ff5a-11e9-9bbd-3bbb7da705fb.png)

**Comment by ahamed** [comment]
In which case you got this error? In my end, I don't get any error. @astridx

**Comment by astridx** [comment]
For example if I click on `close` after I opened `Meet Joomlers `for editing.
![Modules  Administrator Dashboard Menu   test   Administration](https://user-images.githubusercontent.com/9974686/68281188-642cfe80-0077-11ea-9a38-2d6106a0aa31.png)

**Comment by ahamed** [comment]
I did it many times but no error happens.

**Comment by astridx** [comment]
Perhaps it is my fault. If you are sure that everything is fine you can close this issue.

**Comment by ahamed** [comment]
> Perhaps it is my fault. If you are sure that everything is fine you can close this issue.

@marcodings

**Comment by marcodings** [comment]
Closing on request
