### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by Hackwar** [joomla-projects/j4adminui#39]
Please fix all the codestyle issues that our CI is reporting: https://ci.joomla.org/joomla-projects/j4adminui/22/1/9

**Comment by Hackwar** [comment]
The passing of all CI tests is mandatory for this to be accepted.

**Comment by brianteeman** [comment]
codestyle is the least of the issues that this template has

**Comment by Hackwar** [comment]
My hat is that of the ATT lead, so I have to ensure that the result of our CI system is looked at and honoured.
