### ISSUE TITLE
After installing Blog sample data shows again in the dashboard

### ISSUE THREAD

**Issue by arunsasi** [joomla-projects/j4adminui#4]
Install Blog sample data shows again in the dashboard after installation. Disable the install button or show as **INSTALLED**
![screenshot-localhost_8888-2019 10 18-23_19_39](https://user-images.githubusercontent.com/270789/67116542-3d10a900-f1fe-11e9-886c-a23d84b4627e.png)

**Comment by kawshar** [comment]
This is not an issue but a feature ;). You can remove this module from the settings icon.

**Comment by marcodings** [comment]
@kawshar The feedback is not on the "sample data" module as such. Its about the representation of the actual status. Imho arunsi rightfully remarks that once the "Blog Sample Data" is installed, the module should reflect that status.

**Comment by kawshar** [comment]
@marcodings we did not touch the core. I think the developer who developed this feature should take care of it. I checked again, there is no such "status' available when I print the value.

Thanks

**Comment by brianteeman** [comment]
thats really beyond the scope of a template and is feature creep. If you feel it is an issue then it should be opened in the joomla repo
