### ISSUE TITLE
Default Editor not loading in dashboard module

### ISSUE THREAD

**Issue by arunsasi** [joomla-projects/j4adminui#5]
Default Editor not loading **Create an article module** in the dashboard

![screenshot-localhost_8888-2019 10 21-12_40_51](https://user-images.githubusercontent.com/270789/67183951-3ea9bf00-f400-11e9-9758-24488530ac1d.png)

**Comment by kawshar** [comment]
That was intentional. This module is here to create a quick article. Editor will make it complex.
