### ISSUE TITLE
Collapsed sidebar aaccessibility

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/j4adminui#67]
### Steps to reproduce the issue
Go to any page with the sidebar menu in a collapsed state such as New Article

### Expected result
Disabled menu item buttons are **not** in the tab tree

### Actual result
They are in the tab tree and it takes **20** tabs to get to the content

![image](https://user-images.githubusercontent.com/1296369/69329899-d7269f80-0c49-11ea-8c05-f644f4630a0b.png)

**Comment by kawshar** [comment]
Some modules from the status position will be removed in the final build if approved.

**Comment by imarklee** [comment]
The fix on #66 to remove the href when it is disabled should also address this.
