### ISSUE TITLE
Disabled state for header is not visible

### ISSUE THREAD

**Issue by imarklee** [joomla-projects/j4adminui#78]
### Steps to reproduce the issue
Create or edit an article, the disabled state is not the same as the dropdown for the author name.

### Expected result
Private messages and post installation messages should be dimmed.

### Actual result
* Active State
<img width="915" alt="header_active" src="https://user-images.githubusercontent.com/892204/69363464-85bef480-0ccb-11ea-8bf4-6e4f0095214d.png">

* Disabled State
<img width="1041" alt="header_disabled" src="https://user-images.githubusercontent.com/892204/69363465-85bef480-0ccb-11ea-8fd6-14b227d9d8ce.png">

**Comment by kawshar** [comment]
Those modules will be removed. They are available in the menu.

**Comment by imarklee** [comment]
Got it, will close this.
