### ISSUE TITLE
The dashboard's card collapse/expand not working.

### ISSUE THREAD

**Issue by ahamed** [joomla-projects/j4adminui#85]
### Steps to reproduce the issue
Clicking on the card header's top right arrow button does nothing.
<img width="542" alt="card" src="https://user-images.githubusercontent.com/5783354/69400880-7072b600-0d1d-11ea-86ca-231b50100c0e.png">

### Expected result
The card body should be collapsed or expanded.

### Actual result
Nothing happens.

**Comment by imarklee** [comment]
Clicking on the icon does toggle the display correctly. However, there is some strange UI quirkiness, https://take.ms/oelR1 

Should modules placed on the right stick to the right or should they be floated towards the left?

**Comment by kawshar** [comment]
.card-columns has some issues. Need to get rid of the .card-columns structure.
